In [54]:
import pandas as pd

## Q1. Pandas version 

In [55]:
pd.__version__

'2.3.2'

In [57]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-23 15:15:10--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.008s  

2025-09-23 15:15:10 (107 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



## Q2. Records count
How many records are in the dataset?

In [58]:
df= pd.read_csv('car_fuel_efficiency.csv')

In [59]:
df.shape

(9704, 11)

In [60]:
# number of records 
print(f"number of records in the dataset: {df.shape[0]}")

number of records in the dataset: 9704


## Q3. Fuel types
How many fuel types are presented in the dataset?

In [61]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [62]:
print(f"there are {df['fuel_type'].nunique()} fuel types in the dataset")

there are 2 fuel types in the dataset


## Q4. Missing values
How many columns in the dataset have missing values?

In [77]:
missing_cols_count = df.isnull().any().sum()
print(f"Number of columns with missing values: {missing_cols_count}")

Number of columns with missing values: 4


## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [ ]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [90]:
print(df[['origin', 'fuel_efficiency_mpg']][df['origin']=='Asia'].fuel_efficiency_mpg.max())

23.759122836520497


## Q6. Median value of horsepower

Find the median value of horsepower column in the dataset.

In [91]:
df.horsepower.median()

np.float64(149.0)

Next, calculate the most frequent value of the same horsepower column.

In [92]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [93]:
most_freq_hp = df.horsepower.mode()[0]
print(f"Most frequent horsepower value: {most_freq_hp}")

Most frequent horsepower value: 152.0



Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.

In [94]:
df['horsepower']= df['horsepower'].fillna(most_freq_hp)

Now, calculate the median value of horsepower once again.

In [95]:
df.horsepower.median()

np.float64(152.0)

Has it changed?

Yes, it increased

## Q7. Sum of weights

Select all the cars from Asia

In [97]:
df[df['origin']=='Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

Select only columns vehicle_weight and model_year

In [98]:
df[['vehicle_weight','model_year']]

vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

Select the first 7 values

In [99]:
df.head(n=7)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0       152.0     2542.392402   
4                  210            1.0       140.0     3460.870990   
5                  190            3.0       152.0     2484.883986   
6                  240            7.0       127.0     3006.542287   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   
5          14.7        2008  Europe  Gasoline    All-wheel drive       -1.0   
6          22.2        2012     USA  Gasoline  Front-wheel drive        1.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369  
5            17.271818  
6            13.210412

Get the underlying NumPy array. Let's call it X.

In [101]:
X = df[['vehicle_weight', 'model_year']].head(7).values

In [102]:
X

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.

In [114]:
X.T.dot(X)

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [104]:
import numpy as np

In [105]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.


In [117]:
w= np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
w

array([0.07099685, 0.41931263])

What's the sum of all the elements of the result?

0.051
0.51
5.1
51

In [118]:
w.sum()

np.float64(0.4903094879707426)