In [1]:
import numpy as np 

In [2]:
np.__version__

'2.3.3'

## np.zeros

In [3]:
zeros_matrix = np.zeros((3, 4))
zeros_array = np.zeros(5)

print("3x4 Zeros Matrix:\n", zeros_matrix   )
print("1D Zeros Array of length 5:\n", zeros_array)

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1D Zeros Array of length 5:
 [0. 0. 0. 0. 0.]


## np.Ones

In [4]:
ones_matrix = np.ones((3, 4))
ones_array = np.ones(5)

print("3x4 Zeros Matrix:\n", zeros_matrix   )
print("1D Zeros Array of length 5:\n", zeros_array)

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1D Zeros Array of length 5:
 [0. 0. 0. 0. 0.]


## np.full

In [5]:
constant_array = np.full((2,10), 3)  #full(shape, fill_value)
print("1D Array of length 10 with all elements as 3:\n", constant_array)

1D Array of length 10 with all elements as 3:
 [[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]


## Converting List to array 

In [6]:
list=[1, 2, 3, 4, 5]
array_form = np.array(list)
print("List converted to Array:\n", array_form)

List converted to Array:
 [1 2 3 4 5]


## Generating Ranges of numbers 

In [7]:
range_array = np.arange(0, 20, 2)  #arange(start, stop_exclu, step)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Creating Arrays with Linear Spacing
np.linspace() creates arrays with evenly spaced numbers within a specified range:

In [8]:
linspace_array = np.linspace(0, 1, 2)  #linspace(start, stop_inclu, num)
linspace_array                          # step = (stop - start) / (num - 1)

array([0., 1.])

## Indexing and Slicing Arrays

In [9]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

first_row, first_col

(array([2, 3, 4]), array([2, 4]))

## Generating Random Arrays

In [10]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [11]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
normal_distribution, random_integers

(array([[ 0.55145404,  2.29220801],
        [ 0.04153939, -1.11792545],
        [ 0.53905832, -0.5961597 ],
        [-0.0191305 ,  1.17500122],
        [-0.74787095,  0.00902525]]),
 array([[83, 31],
        [66, 80],
        [52, 76],
        [50,  4],
        [90, 63]]))

## Array Operations 

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr + 1   # Adds 1 to each element
arr = arr * 2   # Multiplies each element by 2
# Similar operations for division and exponentiation

arr

array([ 4,  6,  8, 10, 12])

In [13]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
print(result) 
result = arr1 / arr2  # Element-wise division

print("arr11",arr1)
print("arr2",arr2)
result 

[4. 4. 4. 4.]
arr11 [1. 1. 1. 1.]
arr2 [3 3 3 3]


array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

### Comparaison Operations

In [14]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]
equal_to_3 = arr == 3     # Produces [False, False, True, False]
greater_than_2, equal_to_3

(array([False, False,  True,  True]), array([False, False,  True, False]))

### Selecting Elements Based on conditions

In [15]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1
selected_elements

array([2, 3, 4])

### Summary Operations 

In [16]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation == bechhal kaybe3do les valeurrs en moyennes ela la moyenne
min_value, max_value, sum_value, mean_value, std_deviation

(np.int64(1),
 np.int64(4),
 np.int64(10),
 np.float64(2.5),
 np.float64(1.118033988749895))

# About Pandas

In [19]:
import pandas as pd

In [20]:
pd.__version__

'2.3.2'

## Data Frame 
A DataFrame is a tabular data structure commonly used in data analysis (especially with pandas in Python). Think of it like an Excel spreadsheet or a SQL table

In [21]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [24]:
df=pd.DataFrame(data)
df

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [25]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [28]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [29]:
df= pd.DataFrame(data)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [30]:
df.head()  # First 5 rows

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

in pandas , every column of the DataFrame is a series

In [32]:
df.Make  # Accessing a column
df['Engine HP']  # Accessing a column with space in its name

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [34]:
df[['Make', 'Model', 'Year']]  # Accessing multiple columns

Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

## Index

we can use index to access elements of the data frame 

In [38]:
df.loc[1]  # Accessing row with index 1

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                        1002
Name: 1, dtype: object

In [39]:
df.loc[[1, 3]]  # Accessing multiple rows

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP    id  
1         Sedan  27150  1002  
3       4dr SUV  34450  1004

In [40]:
# we can also change the index by using df.index = ...

In [ ]:
# also we can talk about positional indexing with iloc(positional index this is what we usually use in lists and arrays)