In [2]:
import numpy as np 

In [3]:
np.__version__

'2.3.3'

## np.zeros

In [3]:
zeros_matrix = np.zeros((3, 4))
zeros_array = np.zeros(5)

print("3x4 Zeros Matrix:\n", zeros_matrix   )
print("1D Zeros Array of length 5:\n", zeros_array)

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1D Zeros Array of length 5:
 [0. 0. 0. 0. 0.]


## np.Ones

In [4]:
ones_matrix = np.ones((3, 4))
ones_array = np.ones(5)

print("3x4 Zeros Matrix:\n", zeros_matrix   )
print("1D Zeros Array of length 5:\n", zeros_array)

3x4 Zeros Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1D Zeros Array of length 5:
 [0. 0. 0. 0. 0.]


## np.full

In [5]:
constant_array = np.full((2,10), 3)  #full(shape, fill_value)
print("1D Array of length 10 with all elements as 3:\n", constant_array)

1D Array of length 10 with all elements as 3:
 [[3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3]]


## Converting List to array 

In [6]:
list=[1, 2, 3, 4, 5]
array_form = np.array(list)
print("List converted to Array:\n", array_form)

List converted to Array:
 [1 2 3 4 5]


## Generating Ranges of numbers 

In [7]:
range_array = np.arange(0, 20, 2)  #arange(start, stop_exclu, step)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Creating Arrays with Linear Spacing
np.linspace() creates arrays with evenly spaced numbers within a specified range:

In [8]:
linspace_array = np.linspace(0, 1, 2)  #linspace(start, stop_inclu, num)
linspace_array                          # step = (stop - start) / (num - 1)

array([0., 1.])

## Indexing and Slicing Arrays

In [9]:
arr = np.array([[2, 3, 4], [4, 5, 6]])
first_row = arr[0]      # Gets the first row
first_col = arr[:, 0]  # Gets the first column

first_row, first_col

(array([2, 3, 4]), array([2, 4]))

## Generating Random Arrays

In [10]:
np.random.seed(2)  # Set the seed
random_array = np.random.rand(5, 2)  # Generates random numbers between 0 and 1
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [11]:
normal_distribution = np.random.randn(5, 2)
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
normal_distribution, random_integers

(array([[ 0.55145404,  2.29220801],
        [ 0.04153939, -1.11792545],
        [ 0.53905832, -0.5961597 ],
        [-0.0191305 ,  1.17500122],
        [-0.74787095,  0.00902525]]),
 array([[83, 31],
        [66, 80],
        [52, 76],
        [50,  4],
        [90, 63]]))

## Array Operations 

In [12]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr + 1   # Adds 1 to each element
arr = arr * 2   # Multiplies each element by 2
# Similar operations for division and exponentiation

arr

array([ 4,  6,  8, 10, 12])

In [13]:
arr1 = np.ones(4)
arr2 = np.full(4, 3)
result = arr1 + arr2  # Element-wise addition
print(result) 
result = arr1 / arr2  # Element-wise division

print("arr11",arr1)
print("arr2",arr2)
result 

[4. 4. 4. 4.]
arr11 [1. 1. 1. 1.]
arr2 [3 3 3 3]


array([0.33333333, 0.33333333, 0.33333333, 0.33333333])

### Comparaison Operations

In [14]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]
equal_to_3 = arr == 3     # Produces [False, False, True, False]
greater_than_2, equal_to_3

(array([False, False,  True,  True]), array([False, False,  True, False]))

### Selecting Elements Based on conditions

In [15]:
selected_elements = arr[arr > 1]  # Gets elements greater than 1
selected_elements

array([2, 3, 4])

### Summary Operations 

In [16]:
min_value = arr.min()    # Minimum value
max_value = arr.max()    # Maximum value
sum_value = arr.sum()    # Sum of all elements
mean_value = arr.mean()  # Mean (average) value
std_deviation = arr.std()  # Standard deviation == bechhal kaybe3do les valeurrs en moyennes ela la moyenne
min_value, max_value, sum_value, mean_value, std_deviation

(np.int64(1),
 np.int64(4),
 np.int64(10),
 np.float64(2.5),
 np.float64(1.118033988749895))

# About Pandas

In [4]:
import pandas as pd

In [5]:
pd.__version__

'2.3.2'

## Data Frame 
A DataFrame is a tabular data structure commonly used in data analysis (especially with pandas in Python). Think of it like an Excel spreadsheet or a SQL table

In [6]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [7]:
df=pd.DataFrame(data)
df

0         1     2      3  4          5            6      7
0   Nissan    Stanza  1991  138.0  4     MANUAL        sedan   2000
1  Hyundai    Sonata  2017    NaN  4  AUTOMATIC        Sedan  27150
2    Lotus     Elise  2010  218.0  4     MANUAL  convertible  54990
3      GMC    Acadia  2017  194.0  4  AUTOMATIC      4dr SUV  34450
4   Nissan  Frontier  2017  261.0  6     MANUAL       Pickup  32340

In [8]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [9]:
data = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [10]:
df= pd.DataFrame(data)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [11]:
df.head()  # First 5 rows

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

in pandas , every column of the DataFrame is a series

In [12]:
df.Make  # Accessing a column
df['Engine HP']  # Accessing a column with space in its name

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [13]:
df[['Make', 'Model', 'Year']]  # Accessing multiple columns

Make     Model  Year
0   Nissan    Stanza  1991
1  Hyundai    Sonata  2017
2    Lotus     Elise  2010
3      GMC    Acadia  2017
4   Nissan  Frontier  2017

## Index

we can use index to access elements of the data frame 

In [14]:
df.loc[1]  # Accessing row with index 1

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [15]:
df.loc[[1, 3]]  # Accessing multiple rows

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
3      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
1         Sedan  27150  
3       4dr SUV  34450

In [16]:
# we can also change the index by using df.index = ...

In [18]:
df.index=['first', 'second', 'third', 'fourth', 'fifth']
df

Make     Model  Year  Engine HP  Engine Cylinders  \
first    Nissan    Stanza  1991      138.0                 4   
second  Hyundai    Sonata  2017        NaN                 4   
third     Lotus     Elise  2010      218.0                 4   
fourth      GMC    Acadia  2017      194.0                 4   
fifth    Nissan  Frontier  2017      261.0                 6   

       Transmission Type Vehicle_Style   MSRP  
first             MANUAL         sedan   2000  
second         AUTOMATIC         Sedan  27150  
third             MANUAL   convertible  54990  
fourth         AUTOMATIC       4dr SUV  34450  
fifth             MANUAL        Pickup  32340

In [19]:
# also we can talk about positional indexing with iloc(positional index this is what we usually use in lists and arrays) and we use df.iloc
df.iloc[[0, 2]]  # Accessing first and third rows by position   


Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
first  Nissan  Stanza  1991      138.0                 4            MANUAL   
third   Lotus   Elise  2010      218.0                 4            MANUAL   

      Vehicle_Style   MSRP  
first         sedan   2000  
third   convertible  54990

In [20]:
df.iloc[[0, 2], [1, 3]]  # Accessing specific rows and columns by position

Model  Engine HP
first  Stanza      138.0
third   Elise      218.0

In [26]:
# to reset the index to default we use df.reset_index(drop=True)
df= df.reset_index(drop=True) # ou bien juste df.reset_index(drop=True, inplace=True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Operations

In [27]:
df['Engine HP'] > 200  # Boolean mask for rows where 'Engine HP' > 200

0    False
1    False
2     True
3    False
4     True
Name: Engine HP, dtype: bool

In [28]:
df['Engine HP']/100

0    1.38
1     NaN
2    2.18
3    1.94
4    2.61
Name: Engine HP, dtype: float64

## Filtring

In [31]:
display(df[df['Make'] == 'Nissan'] ) # Filtering rows where Make is Nissan

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  Nissan    Stanza  1991      138.0                 4            MANUAL   
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
4        Pickup  32340

In [34]:
display(df[(df['Make'] == 'Nissan' )& (df['Year']==2017)] )

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

## String Operations

In [35]:
df['Vehicle_Style']

0          sedan
1          Sedan
2    convertible
3        4dr SUV
4         Pickup
Name: Vehicle_Style, dtype: object

In [40]:
# we use lower() to convert all strings in a column to lowercase for standardization of writing 
df['Vehicle_Style']= df['Vehicle_Style'].str.lower()

In [41]:
# .replace('a','b') to replace a by b 
df['Vehicle_Style']= df['Vehicle_Style'].str.replace(' ','_')

In [42]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         sedan  27150  
2   convertible  54990  
3       4dr_suv  34450  
4        pickup  32340

In [ ]:
# also we can use directaly this lambda function df['Vehicle_Style'] = df['Vehicle_Style'].apply(lambda x: x.lower().replace(' ', '_'))

## Summarising Operaters 

In [43]:
df['MSRP'].describe()  # Summary statistics for 'MSRP' column

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [44]:
# to know how many unique values are in a column we use .nunique()
df['Make'].nunique()  # Number of unique car makes

4

In [45]:
#.nunique() counts the number of distinct elements in a column, ignoring duplicates.we can also apply it the entire dataframe to get the number of unique values in each column
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

## Missing Values 

In [46]:
#.isnull() to check for missing values in a column, it returns a new dataframe of the same shape with boolean values indicating whether each element is null (True) or not (False).
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [47]:
# How can we know how many missing values are in each column?
df.isnull().sum()  # Sum of null values in each column

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

## Grouping 

In [50]:
df.groupby('Transmission Type')['MSRP'].mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

## Getting the numpy array

In [52]:
df.MSRP.values  # Gets the underlying numpy array of 'MSRP' column

array([ 2000, 27150, 54990, 34450, 32340])

In [53]:
# Convert DataFrame to a list of dict by using df.to_dict(orient='records')
df.to_dict(orient='records')  # Each row as a dictionary in a list

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]